# Site settings
title: ISYS 115 Programming Logic and Design
description: "Notes and projects for ISYS 115: foundational concepts in programming logic, problem-solving, and introductory JavaScript."
#baseurl: ""
#url: "127.0.0.1:4001"
url: "https://isys115.nicholasstull.com"
homeurl: "https://isys115.nicholasstull.com"

# Social media
github_username: tinkernerd
linkedin_username: nicholaspstull
# Contact Me
phone: 2694877564
email: nicholasp.stull@gmail.com

# Build settings
markdown: kramdown
permalink: pretty

# Syntax highlighting
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

